apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: {{ .Values.database.service.type}}
  ports:
    - port: {{ .Values.database.service.port}}
      targetPort: {{ .Values.database.service.targetPort}}
  selector:
    app: mysql