name: Update Deployment to Latest Image

on:
  workflow_dispatch:
    inputs:
      deployment_name:
        type: choice
        required: true
        description: Name of the deployment to update the image, must be `frontend` or `backend`
        options:
        - frontend
        - backend

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}

jobs:
  update-deployment:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'latest'

    - name: Update deployment
      run: |
        kubectl rollout restart deployment/${{ github.event.inputs.deployment_name }}

    - name: Verify rollout
      run: |
        kubectl rollout status deployment/${{ github.event.inputs.deployment_name }} --timeout=300s
